import { type Iphone } from '../types/Iphone'

const iphone15Url = 'https://support.apple.com/111831'
const iphone15PlusUrl = 'https://support.apple.com/111830'
const iphone15ProUrl = 'https://support.apple.com/111829'
const iphone15ProMaxUrl = 'https://support.apple.com/111828'

export const iphone15List: Iphone[] = [
  {
    model: 'iphone-15',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 29_900 },
    isInitialRelease: true,
    url: iphone15Url,
  },
  {
    model: 'iphone-15',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 33_400 },
    isInitialRelease: true,
    url: iphone15Url,
  },
  {
    model: 'iphone-15',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 40_400 },
    isInitialRelease: true,
    url: iphone15Url,
  },

  {
    model: 'iphone-15-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 32_900 },
    isInitialRelease: true,
    url: iphone15PlusUrl,
  },
  {
    model: 'iphone-15-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 36_400 },
    isInitialRelease: true,
    url: iphone15PlusUrl,
  },
  {
    model: 'iphone-15-plus',
    storage: 512,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 43_400 },
    isInitialRelease: true,
    url: iphone15PlusUrl,
  },

  {
    model: 'iphone-15-pro',
    storage: 128,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 36_900 },
    isInitialRelease: true,
    url: iphone15ProUrl,
  },
  {
    model: 'iphone-15-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 40_400 },
    isInitialRelease: true,
    url: iphone15ProUrl,
  },
  {
    model: 'iphone-15-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 47_400 },
    isInitialRelease: true,
    url: iphone15ProUrl,
  },
  {
    model: 'iphone-15-pro',
    storage: 1024,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 54_400 },
    isInitialRelease: true,
    url: iphone15ProUrl,
  },

  {
    model: 'iphone-15-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2023-09',
    price: { twd: 44_900 },
    isInitialRelease: true,
    url: iphone15ProMaxUrl,
  },
  {
    model: 'iphone-15-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2023-09',
    price: { twd: 51_900 },
    isInitialRelease: true,
    url: iphone15ProMaxUrl,
  },
  {
    model: 'iphone-15-pro-max',
    storage: 1024,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2023-09',
    price: { twd: 58_900 },
    isInitialRelease: true,
    url: iphone15ProMaxUrl,
  },

  {
    model: 'iphone-15',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 25_900 },
    url: iphone15Url,
  },
  {
    model: 'iphone-15',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 29_400 },
    url: iphone15Url,
  },
  {
    model: 'iphone-15',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 36_400 },
    url: iphone15Url,
  },

  {
    model: 'iphone-15-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 29_900 },
    url: iphone15PlusUrl,
  },
  {
    model: 'iphone-15-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 33_400 },
    url: iphone15PlusUrl,
  },
  {
    model: 'iphone-15-plus',
    storage: 512,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 40_400 },
    url: iphone15PlusUrl,
  },
]
