import { type Iphone } from '../types/Iphone'

const iphone17Url = 'https://www.apple.com/tw/iphone-17/specs/'
const iphone17AirUrl = 'https://www.apple.com/tw/iphone-air/specs/'
const iphone17ProUrl = 'https://www.apple.com/tw/iphone-17-pro/specs/'
const iphone17ProMaxUrl = 'https://www.apple.com/tw/iphone-17-pro/specs/'

export const iphone17List: Iphone[] = [
  {
    model: 'iphone-17',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2025-09',
    price: { twd: 29_900 },
    isInitialRelease: true,
    url: iphone17Url,
  },
  {
    model: 'iphone-17',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2025-09',
    price: { twd: 36_900 },
    isInitialRelease: true,
    url: iphone17Url,
  },

  {
    model: 'iphone-17-air',
    storage: 256,
    line: 'premium',
    suffix: 'air',
    releasedAt: '2025-09',
    price: { twd: 36_900 },
    isInitialRelease: true,
    url: iphone17AirUrl,
  },
  {
    model: 'iphone-17-air',
    storage: 512,
    line: 'premium',
    suffix: 'air',
    releasedAt: '2025-09',
    price: { twd: 43_900 },
    isInitialRelease: true,
    url: iphone17AirUrl,
  },
  {
    model: 'iphone-17-air',
    storage: 1024,
    line: 'premium',
    suffix: 'air',
    releasedAt: '2025-09',
    price: { twd: 50_900 },
    isInitialRelease: true,
    url: iphone17AirUrl,
  },

  {
    model: 'iphone-17-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2025-09',
    price: { twd: 39_900 },
    isInitialRelease: true,
    url: iphone17ProUrl,
  },
  {
    model: 'iphone-17-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2025-09',
    price: { twd: 46_900 },
    isInitialRelease: true,
    url: iphone17ProUrl,
  },
  {
    model: 'iphone-17-pro',
    storage: 1024,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2025-09',
    price: { twd: 53_900 },
    isInitialRelease: true,
    url: iphone17ProUrl,
  },

  {
    model: 'iphone-17-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2025-09',
    price: { twd: 44_900 },
    isInitialRelease: true,
    url: iphone17ProMaxUrl,
  },
  {
    model: 'iphone-17-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2025-09',
    price: { twd: 51_900 },
    isInitialRelease: true,
    url: iphone17ProMaxUrl,
  },
  {
    model: 'iphone-17-pro-max',
    storage: 1024,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2025-09',
    price: { twd: 58_900 },
    isInitialRelease: true,
    url: iphone17ProMaxUrl,
  },
  {
    model: 'iphone-17-pro-max',
    storage: 2048,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2025-09',
    price: { twd: 72_900 },
    isInitialRelease: true,
    url: iphone17ProMaxUrl,
  },
]
