import { type Iphone } from '../types/Iphone'

export const iphone6sList: Iphone[] = [
  {
    model: 'iphone-6s',
    storage: 16,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2015-10',
    price: { twd: 24_500 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-6s',
    storage: 64,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2015-10',
    price: { twd: 28_500 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-6s',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2015-10',
    price: { twd: 32_500 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-6s',
    storage: 32,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2016-09',
    price: { twd: 20_500 },
  },
  {
    model: 'iphone-6s',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2016-09',
    price: { twd: 24_500 },
  },

  {
    model: 'iphone-6s',
    storage: 32,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2017-09',
    price: { twd: 16_500 },
  },
  {
    model: 'iphone-6s',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2017-09',
    price: { twd: 19_900 },
  },

  {
    model: 'iphone-6s-plus',
    storage: 16,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2015-10',
    price: { twd: 28_500 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-6s-plus',
    storage: 64,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2015-10',
    price: { twd: 32_500 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-6s-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2015-10',
    price: { twd: 36_500 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-6s-plus',
    storage: 32,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2016-09',
    price: { twd: 24_500 },
  },
  {
    model: 'iphone-6s-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2016-09',
    price: { twd: 28_500 },
  },

  {
    model: 'iphone-6s-plus',
    storage: 32,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2017-09',
    price: { twd: 19_900 },
  },
  {
    model: 'iphone-6s-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2017-09',
    price: { twd: 23_500 },
  },
]
