import { type Iphone } from '../types/Iphone'

const iphone16Url = 'https://support.apple.com/121029'
const iphone16PlusUrl = 'https://support.apple.com/121030'
const iphone16ProUrl = 'https://support.apple.com/121031'
const iphone16ProMaxUrl = 'https://support.apple.com/121032'

export const iphone16List: Iphone[] = [
  {
    model: 'iphone-16',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 29_900 },
    isInitialRelease: true,
    url: iphone16Url,
  },
  {
    model: 'iphone-16',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 33_400 },
    isInitialRelease: true,
    url: iphone16Url,
  },
  {
    model: 'iphone-16',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 40_400 },
    isInitialRelease: true,
    url: iphone16Url,
  },

  {
    model: 'iphone-16-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 32_900 },
    isInitialRelease: true,
    url: iphone16PlusUrl,
  },
  {
    model: 'iphone-16-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 36_400 },
    isInitialRelease: true,
    url: iphone16PlusUrl,
  },
  {
    model: 'iphone-16-plus',
    storage: 512,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 43_400 },
    isInitialRelease: true,
    url: iphone16PlusUrl,
  },

  {
    model: 'iphone-16-pro',
    storage: 128,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2024-09',
    price: { twd: 36_900 },
    isInitialRelease: true,
    url: iphone16ProUrl,
  },
  {
    model: 'iphone-16-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2024-09',
    price: { twd: 40_400 },
    isInitialRelease: true,
    url: iphone16ProUrl,
  },
  {
    model: 'iphone-16-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2024-09',
    price: { twd: 47_400 },
    isInitialRelease: true,
    url: iphone16ProUrl,
  },
  {
    model: 'iphone-16-pro',
    storage: 1024,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2024-09',
    price: { twd: 54_400 },
    isInitialRelease: true,
    url: iphone16ProUrl,
  },

  {
    model: 'iphone-16-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2024-09',
    price: { twd: 44_900 },
    isInitialRelease: true,
    url: iphone16ProMaxUrl,
  },
  {
    model: 'iphone-16-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2024-09',
    price: { twd: 51_900 },
    isInitialRelease: true,
    url: iphone16ProMaxUrl,
  },
  {
    model: 'iphone-16-pro-max',
    storage: 1024,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2024-09',
    price: { twd: 58_900 },
    isInitialRelease: true,
    url: iphone16ProMaxUrl,
  },

  {
    model: 'iphone-16',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2025-09',
    price: { twd: 25_900 },
    url: iphone16Url,
  },
  {
    model: 'iphone-16-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2025-09',
    price: { twd: 29_900 },
    url: iphone16PlusUrl,
  },
  {
    model: 'iphone-16-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2025-09',
    price: { twd: 33_400 },
    url: iphone16PlusUrl,
  },
]
