import { type Iphone } from '../types/Iphone'

export const iphone15List: Iphone[] = [
  {
    model: 'iphone-15',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 29_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 33_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 40_400 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-15-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 32_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 36_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15-plus',
    storage: 512,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 43_400 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-15-pro',
    storage: 128,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 36_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 40_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 47_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15-pro',
    storage: 1024,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2023-09',
    price: { twd: 54_400 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-15-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2023-09',
    price: { twd: 44_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2023-09',
    price: { twd: 51_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-15-pro-max',
    storage: 1024,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2023-09',
    price: { twd: 58_900 },
    isInitialRelease: true,
  },
]
