import { type Iphone } from '../types/Iphone'

export const iphone12List: Iphone[] = [
  {
    model: 'iphone-12',
    storage: 64,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2020-10',
    price: { twd: 26_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2020-10',
    price: { twd: 28_500 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2020-10',
    price: { twd: 32_000 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-12',
    storage: 64,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 22_900 },
  },
  {
    model: 'iphone-12',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 24_500 },
  },
  {
    model: 'iphone-12',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 28_000 },
  },

  {
    model: 'iphone-12',
    storage: 64,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 20_900 },
  },
  {
    model: 'iphone-12',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 22_500 },
  },
  {
    model: 'iphone-12',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 26_000 },
  },

  {
    model: 'iphone-12-mini',
    storage: 64,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2020-10',
    price: { twd: 23_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12-mini',
    storage: 128,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2020-10',
    price: { twd: 25_500 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12-mini',
    storage: 256,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2020-10',
    price: { twd: 29_000 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-12-mini',
    storage: 64,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2021-09',
    price: { twd: 19_900 },
  },
  {
    model: 'iphone-12-mini',
    storage: 128,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2021-09',
    price: { twd: 21_500 },
  },
  {
    model: 'iphone-12-mini',
    storage: 256,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2021-09',
    price: { twd: 25_000 },
  },

  {
    model: 'iphone-12-pro',
    storage: 128,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2020-10',
    price: { twd: 33_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2020-10',
    price: { twd: 37_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2020-10',
    price: { twd: 44_400 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-12-pro-max',
    storage: 128,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2020-10',
    price: { twd: 37_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2020-10',
    price: { twd: 41_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-12-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2020-10',
    price: { twd: 48_400 },
    isInitialRelease: true,
  },
]
