import { type Iphone } from '../types/Iphone'

const iphone18ProUrl = 'https://www.apple.com/tw/iphone-18-pro/specs/'
const iphoneDuoUrl = 'https://www.apple.com/tw/iphone-duo/specs/'

export const iphone18List: Iphone[] = [
  {
    model: 'iphone-18-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2026-09',
    price: { twd: 44_900, usd: 1_199 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },
  {
    model: 'iphone-18-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2026-09',
    price: { twd: 51_900, usd: 1_399 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },
  {
    model: 'iphone-18-pro',
    storage: 1024,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2026-09',
    price: { twd: 66_900, usd: 1_799 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },
  {
    model: 'iphone-18-pro',
    storage: 2048,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2026-09',
    price: { twd: 88_900, usd: 2_399 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },

  {
    model: 'iphone-18-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2026-09',
    price: { twd: 49_900, usd: 1_299 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },
  {
    model: 'iphone-18-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2026-09',
    price: { twd: 56_900, usd: 1_499 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },
  {
    model: 'iphone-18-pro-max',
    storage: 1024,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2026-09',
    price: { twd: 71_900, usd: 1_899 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },
  {
    model: 'iphone-18-pro-max',
    storage: 2048,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2026-09',
    price: { twd: 93_900, usd: 2_499 },
    isInitialRelease: true,
    url: iphone18ProUrl,
  },

  {
    model: 'iphone-duo',
    storage: 256,
    line: 'foldable',
    suffix: 'duo',
    releasedAt: '2026-09',
    price: { twd: 74_900, usd: 1_999 },
    isInitialRelease: true,
    url: iphoneDuoUrl,
  },
  {
    model: 'iphone-duo',
    storage: 512,
    line: 'foldable',
    suffix: 'duo',
    releasedAt: '2026-09',
    price: { twd: 81_900, usd: 2_199 },
    isInitialRelease: true,
    url: iphoneDuoUrl,
  },
  {
    model: 'iphone-duo',
    storage: 1024,
    line: 'foldable',
    suffix: 'duo',
    releasedAt: '2026-09',
    price: { twd: 96_900, usd: 2_599 },
    isInitialRelease: true,
    url: iphoneDuoUrl,
  },
  {
    model: 'iphone-duo',
    storage: 2048,
    line: 'foldable',
    suffix: 'duo',
    releasedAt: '2026-09',
    price: { twd: 118_900, usd: 3_199 },
    isInitialRelease: true,
    url: iphoneDuoUrl,
  },
]
