import { type Iphone } from '../types/Iphone'

export const iphone11List: Iphone[] = [
  {
    model: 'iphone-11',
    storage: 64,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2019-09',
    price: { twd: 24_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-11',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2019-09',
    price: { twd: 26_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-11',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2019-09',
    price: { twd: 30_400 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-11',
    storage: 64,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2020-10',
    price: { twd: 19_900 },
  },
  {
    model: 'iphone-11',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2020-10',
    price: { twd: 21_500 },
  },
  {
    model: 'iphone-11',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2020-10',
    price: { twd: 25_000 },
  },

  {
    model: 'iphone-11',
    storage: 64,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 16_500 },
  },
  {
    model: 'iphone-11',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 18_100 },
  },

  {
    model: 'iphone-11-pro',
    storage: 64,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2019-09',
    price: { twd: 35_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-11-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2019-09',
    price: { twd: 41_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-11-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2019-09',
    price: { twd: 48_400 },
    isInitialRelease: true,
  },

  {
    model: 'iphone-11-pro-max',
    storage: 64,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2019-09',
    price: { twd: 39_900 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-11-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2019-09',
    price: { twd: 45_400 },
    isInitialRelease: true,
  },
  {
    model: 'iphone-11-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2019-09',
    price: { twd: 52_400 },
    isInitialRelease: true,
  },
]
