import { type Iphone } from '../types/Iphone'

const iphone7Url = 'https://support.apple.com/111943'
const iphone7PlusUrl = 'https://support.apple.com/111953'

export const iphone7List: Iphone[] = [
  {
    model: 'iphone-7',
    storage: 32,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2016-09',
    price: { twd: 24_500, usd: 649 },
    isInitialRelease: true,
    url: iphone7Url,
  },
  {
    model: 'iphone-7',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2016-09',
    price: { twd: 28_500, usd: 749 },
    isInitialRelease: true,
    url: iphone7Url,
  },
  {
    model: 'iphone-7',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2016-09',
    price: { twd: 32_500, usd: 849 },
    isInitialRelease: true,
    url: iphone7Url,
  },

  {
    model: 'iphone-7',
    storage: 32,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2017-09',
    price: { twd: 19_900, usd: 549 },
    url: iphone7Url,
  },
  {
    model: 'iphone-7',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2017-09',
    price: { twd: 23_500, usd: 649 },
    url: iphone7Url,
  },

  {
    model: 'iphone-7',
    storage: 32,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2018-09',
    price: { twd: 15_900, usd: 449 },
    url: iphone7Url,
  },
  {
    model: 'iphone-7',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2018-09',
    price: { twd: 19_900, usd: 549 },
    url: iphone7Url,
  },

  {
    model: 'iphone-7-plus',
    storage: 32,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2016-09',
    price: { twd: 28_900, usd: 769 },
    isInitialRelease: true,
    url: iphone7PlusUrl,
  },
  {
    model: 'iphone-7-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2016-09',
    price: { twd: 32_900, usd: 869 },
    isInitialRelease: true,
    url: iphone7PlusUrl,
  },
  {
    model: 'iphone-7-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2016-09',
    price: { twd: 36_900, usd: 969 },
    isInitialRelease: true,
    url: iphone7PlusUrl,
  },

  {
    model: 'iphone-7-plus',
    storage: 32,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2017-09',
    price: { twd: 24_500, usd: 669 },
    url: iphone7PlusUrl,
  },
  {
    model: 'iphone-7-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2017-09',
    price: { twd: 28_100, usd: 769 },
    url: iphone7PlusUrl,
  },

  {
    model: 'iphone-7-plus',
    storage: 32,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2018-09',
    price: { twd: 20_500, usd: 569 },
    url: iphone7PlusUrl,
  },
  {
    model: 'iphone-7-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2018-09',
    price: { twd: 24_500, usd: 669 },
    url: iphone7PlusUrl,
  },
]
