import { type Iphone } from '../types/Iphone'

const iphone13Url = 'https://support.apple.com/111872'
const iphone13MiniUrl = 'https://support.apple.com/111873'
const iphone13ProUrl = 'https://support.apple.com/111871'
const iphone13ProMaxUrl = 'https://support.apple.com/111870'

export const iphone13List: Iphone[] = [
  {
    model: 'iphone-13',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 25_900 },
    isInitialRelease: true,
    url: iphone13Url,
  },
  {
    model: 'iphone-13',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 29_400 },
    isInitialRelease: true,
    url: iphone13Url,
  },
  {
    model: 'iphone-13',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2021-09',
    price: { twd: 36_400 },
    isInitialRelease: true,
    url: iphone13Url,
  },

  {
    model: 'iphone-13',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 24_900 },
    url: iphone13Url,
  },
  {
    model: 'iphone-13',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 28_400 },
    url: iphone13Url,
  },
  {
    model: 'iphone-13',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 35_400 },
    url: iphone13Url,
  },

  {
    model: 'iphone-13',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 21_900 },
    url: iphone13Url,
  },
  {
    model: 'iphone-13',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 25_400 },
    url: iphone13Url,
  },
  {
    model: 'iphone-13',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 32_400 },
    url: iphone13Url,
  },

  {
    model: 'iphone-13-mini',
    storage: 128,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2021-09',
    price: { twd: 22_900 },
    isInitialRelease: true,
    url: iphone13MiniUrl,
  },
  {
    model: 'iphone-13-mini',
    storage: 256,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2021-09',
    price: { twd: 26_400 },
    isInitialRelease: true,
    url: iphone13MiniUrl,
  },
  {
    model: 'iphone-13-mini',
    storage: 512,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2021-09',
    price: { twd: 33_400 },
    isInitialRelease: true,
    url: iphone13MiniUrl,
  },

  {
    model: 'iphone-13-mini',
    storage: 128,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2022-09',
    price: { twd: 20_900 },
    url: iphone13MiniUrl,
  },
  {
    model: 'iphone-13-mini',
    storage: 256,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2022-09',
    price: { twd: 24_400 },
    url: iphone13MiniUrl,
  },
  {
    model: 'iphone-13-mini',
    storage: 512,
    line: 'regular',
    suffix: 'mini',
    releasedAt: '2022-09',
    price: { twd: 31_400 },
    url: iphone13MiniUrl,
  },

  {
    model: 'iphone-13-pro',
    storage: 128,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2021-09',
    price: { twd: 32_900 },
    isInitialRelease: true,
    url: iphone13ProUrl,
  },
  {
    model: 'iphone-13-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2021-09',
    price: { twd: 36_400 },
    isInitialRelease: true,
    url: iphone13ProUrl,
  },
  {
    model: 'iphone-13-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2021-09',
    price: { twd: 43_400 },
    isInitialRelease: true,
    url: iphone13ProUrl,
  },
  {
    model: 'iphone-13-pro',
    storage: 1024,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2021-09',
    price: { twd: 50_400 },
    isInitialRelease: true,
    url: iphone13ProUrl,
  },

  {
    model: 'iphone-13-pro-max',
    storage: 128,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2021-09',
    price: { twd: 36_900 },
    isInitialRelease: true,
    url: iphone13ProMaxUrl,
  },
  {
    model: 'iphone-13-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2021-09',
    price: { twd: 40_400 },
    isInitialRelease: true,
    url: iphone13ProMaxUrl,
  },
  {
    model: 'iphone-13-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2021-09',
    price: { twd: 47_400 },
    isInitialRelease: true,
    url: iphone13ProMaxUrl,
  },
  {
    model: 'iphone-13-pro-max',
    storage: 1024,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2021-09',
    price: { twd: 54_400 },
    isInitialRelease: true,
    url: iphone13ProMaxUrl,
  },
]
