import { type Iphone } from '../types/Iphone'

const iphone14Url = 'https://support.apple.com/111850'
const iphone14PlusUrl = 'https://support.apple.com/111854'
const iphone14ProUrl = 'https://support.apple.com/111849'
const iphone14ProMaxUrl = 'https://support.apple.com/111846'

export const iphone14List: Iphone[] = [
  {
    model: 'iphone-14',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 27_900 },
    isInitialRelease: true,
    url: iphone14Url,
  },
  {
    model: 'iphone-14',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 31_400 },
    isInitialRelease: true,
    url: iphone14Url,
  },
  {
    model: 'iphone-14',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2022-09',
    price: { twd: 38_400 },
    isInitialRelease: true,
    url: iphone14Url,
  },

  {
    model: 'iphone-14',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 25_900 },
    url: iphone14Url,
  },
  {
    model: 'iphone-14',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 29_400 },
    url: iphone14Url,
  },
  {
    model: 'iphone-14',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2023-09',
    price: { twd: 36_400 },
    url: iphone14Url,
  },

  {
    model: 'iphone-14',
    storage: 128,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 21_900 },
    url: iphone14Url,
  },
  {
    model: 'iphone-14',
    storage: 256,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 25_400 },
    url: iphone14Url,
  },
  {
    model: 'iphone-14',
    storage: 512,
    line: 'regular',
    suffix: 'base',
    releasedAt: '2024-09',
    price: { twd: 32_400 },
    url: iphone14Url,
  },

  {
    model: 'iphone-14-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2022-09',
    price: { twd: 31_900 },
    isInitialRelease: true,
    url: iphone14PlusUrl,
  },
  {
    model: 'iphone-14-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2022-09',
    price: { twd: 35_400 },
    isInitialRelease: true,
    url: iphone14PlusUrl,
  },
  {
    model: 'iphone-14-plus',
    storage: 512,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2022-09',
    price: { twd: 42_400 },
    isInitialRelease: true,
    url: iphone14PlusUrl,
  },

  {
    model: 'iphone-14-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 29_900 },
    url: iphone14PlusUrl,
  },
  {
    model: 'iphone-14-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 33_400 },
    url: iphone14PlusUrl,
  },
  {
    model: 'iphone-14-plus',
    storage: 512,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2023-09',
    price: { twd: 40_400 },
    url: iphone14PlusUrl,
  },

  {
    model: 'iphone-14-plus',
    storage: 128,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 25_900 },
    url: iphone14PlusUrl,
  },
  {
    model: 'iphone-14-plus',
    storage: 256,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 29_400 },
    url: iphone14PlusUrl,
  },
  {
    model: 'iphone-14-plus',
    storage: 512,
    line: 'regular',
    suffix: 'plus',
    releasedAt: '2024-09',
    price: { twd: 36_400 },
    url: iphone14PlusUrl,
  },

  {
    model: 'iphone-14-pro',
    storage: 128,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2022-09',
    price: { twd: 34_900 },
    isInitialRelease: true,
    url: iphone14ProUrl,
  },
  {
    model: 'iphone-14-pro',
    storage: 256,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2022-09',
    price: { twd: 38_400 },
    isInitialRelease: true,
    url: iphone14ProUrl,
  },
  {
    model: 'iphone-14-pro',
    storage: 512,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2022-09',
    price: { twd: 45_400 },
    isInitialRelease: true,
    url: iphone14ProUrl,
  },
  {
    model: 'iphone-14-pro',
    storage: 1024,
    line: 'premium',
    suffix: 'pro',
    releasedAt: '2022-09',
    price: { twd: 52_400 },
    isInitialRelease: true,
    url: iphone14ProUrl,
  },

  {
    model: 'iphone-14-pro-max',
    storage: 128,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2022-09',
    price: { twd: 38_900 },
    isInitialRelease: true,
    url: iphone14ProMaxUrl,
  },
  {
    model: 'iphone-14-pro-max',
    storage: 256,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2022-09',
    price: { twd: 42_400 },
    isInitialRelease: true,
    url: iphone14ProMaxUrl,
  },
  {
    model: 'iphone-14-pro-max',
    storage: 512,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2022-09',
    price: { twd: 49_400 },
    isInitialRelease: true,
    url: iphone14ProMaxUrl,
  },
  {
    model: 'iphone-14-pro-max',
    storage: 1024,
    line: 'premium',
    suffix: 'pro-max',
    releasedAt: '2022-09',
    price: { twd: 56_400 },
    isInitialRelease: true,
    url: iphone14ProMaxUrl,
  },
]
